site_name: lo3
site_url: https://lo3-lang.github.io/wiki/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
nav:
  - Home: index.md
  - Syntax: syntax.md
  - Examples: examples.md
  - Wiki:
    - FAQ: wiki/faq.md
    - Internals: wiki/internals.md
